dataset:
  train_set : dataset/DBPEDIA_train.csv
  val_set   : dataset/DBPEDIA_val.csv
  test_set  : dataset/DBPEDIA_test.csv
  stop_words: dataset/stop_words.txt

training:
  log_dir   : "log_l2"
  use_label : l2
  text_len  : 256
  batch     : 128
  train_steps : 500
  update_freq : 100
  epochs    : 1000
  labels    : labels.txt

app:
  host      : "127.0.0.1"
  port      : "56789"
  text_len  : 256
  pretrained: log_l2/weights/0004-0.1552.hdf5
  labels    : log_l2/labels.txt